- name: init k8s
  shell: kubeadm init --image-repository registry.aliyuncs.com/google_containers --kubernetes-version {{ VERSION }} --apiserver-advertise-address {{ MASTER_IP }}  --pod-network-cidr=192.168.0.0/16 --token-ttl 0
  when: ansible_facts.default_ipv4.address == (MASTER_IP)