- name: Master Yum
  yum:
    name:
      - kubelet-{{ VERSION }}
      - kubeadm-{{ VERSION }}
      - kubectl-{{ VERSION }}
    state: present
  when: ansible_facts.default_ipv4.address == (MASTER_IP)