- name: Master hostname
  shell: hostnamectl set-hostname master
  when: ansible_facts.default_ipv4.address == (MASTER_IP)
- name: Node-0 hostname
  shell: hostnamectl set-hostname node-0
  when: ansible_facts.default_ipv4.address == (NODE_0_IP)
- name: Node-1 hostname
  shell: hostnamectl set-hostname node-1
  when: ansible_facts.default_ipv4.address == (NODE_1_IP)