- name: 设置kube-scheduler的systemd服务配置文件
  copy: src=kube-scheduler.service dest=/usr/lib/systemd/system mode=0644
  when: ansible_facts.default_ipv4.address == (MASTER_IP)
- name: 添加kube-scheduler的启动参数
  copy: src=scheduler dest=/etc/kubernetes mode=0644
  when: ansible_facts.default_ipv4.address == (MASTER_IP)
- name: 启动kube-scheduler服务并加入开机启动
  service: name=kube-scheduler state=started enabled=yes
  when: ansible_facts.default_ipv4.address == (MASTER_IP)