- name: 设置kube-proxy的systemd服务配置文件
  copy: src=kube-proxy.service dest=/usr/lib/systemd/system mode=0644
  when: ansible_facts.default_ipv4.address != '192.168.3.10'
- name: 添加kube-proxy的启动参数
  copy: src=proxy dest=/etc/kubernetes
  when: ansible_facts.default_ipv4.address != '192.168.3.10'
- name: 启动kube-proxy服务并加入开机启动
  service: name=kube-proxy state=started enabled=yes
  when: ansible_facts.default_ipv4.address != '192.168.3.10'