- name: 设置kube-apiserver的systemd服务配置文件
  copy: src=kube-apiserver.service dest=/usr/lib/systemd/system mode=0644
  when: ansible_facts.default_ipv4.address == (MASTER_IP)
- name: 添加apiserver的启动参数
  copy: src=apiserver dest=/etc/kubernetes mode=0644
  when: ansible_facts.default_ipv4.address == (MASTER_IP)
- name: 启动kube-apiserver服务并加入开机启动
  service: name=kube-apiserver state=started enabled=yes
  when: ansible_facts.default_ipv4.address == (MASTER_IP)