- name: 移动kube-apiserver、kube-controller-manager、kube-scheduler组件到/usr/bin目录
  shell: chdir=/tmp/kubernetes/server/bin/ cp kube-apiserver kube-controller-manager kube-scheduler /usr/bin/
  when: ansible_facts.default_ipv4.address == (MASTER_IP)